### ISSUE TITLE
Solution to product_of_all_other_elements.go is not in O(n)

### ISSUE THREAD

**Issue by xavierhazzardadmin** [spring1843/go-dsa#53]
I could be being really stupid. If so please correct me.

I believe that it's impossible to solve product_of_all_other_elements without either using division or going beyond the O(n) requirement.

The solution given in product_of_all_other_elements.go is basically O(2n) which goes against your requirements.

Am I wrong?

**Comment by spring1843** [comment]
You are right that it's O(2n), however constants can be dropped when simplifying Big Oh notations. So O(2n) can be simplified to O(n).
